---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: "pip"
    directory: "/libs/lib1"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: "pip" # salut
    directory: "/libs/lib10"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: "pip"
    directory: "/libs/lib2"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: "pip"
    directory: "/libs/lib3"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: "pip"
    directory: "/libs/lib4"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: "pip"
    directory: "/libs/lib5"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
  - package-ecosystem: "pip"
    directory: "/libs/lib6"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      my-group:
        # A pattern can be...
        patterns:
          - "pip" # a single dependency name
    open-pull-requests-limit: 1000
  - package-ecosystem: "pip"
    directory: "/libs/lib7"
    schedule:
      interval: "daily"
      time: "13:00"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: ":boom: :boom: "
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      my-group:
        # A pattern can be...
        patterns:
          - "pip" # a single dependency name
    open-pull-requests-limit: 1000
