setuptools = "44.0.0"
coloredlogs = "10.0"
Cython = "0.29.14"
pyproj = "3.2.1"
fiona = "1.8.20"
geopandas = "0.7.0"
h5py = "2.10.0"
ipython = "7.28.0"
memory-profiler = "0.55.0"
networkx = "2.5"
psutil = "5.6.7"
pyminizip = "0.2.4"
rasterio = "1.2.6"
sknw = "0.13"
tqdm = "4.41.1"
typing_extensions = "*"
verboselogs = "1.7"
wget = "3.2"
